name: Build Latex GH Action
#adapted from https://github.com/xu-cheng/latex-action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: main.tex
      - name: Compile LaTeX document with pre/post compile actions
        uses: ./
        with:
          root_file: |
            main.tex
          pre_compile: |
            rm thesis.pdf
          post_compile: |
            ls thesis.pdf
            mv thesis.pdf test
      - name: Test Action with Github Default Template
        uses: ./
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex
          compiler: latexmk 
          # Extra arguments to be passed to the LaTeX engine
          args: "--jobname=thesis"
      - name: Check pdf files
        run: |
          file test/thesis.pdf | grep -q ' PDF '
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: thesis.pdf 
          path: ./ 
        if: always()
